### PR TITLE
added dislike counter

### PR DESCRIPTION
**Pull request by andrisas**
added dislike counter using returnyoutubedislike.com API

### CODE REVIEW

**Comment by gzsombor** [comment]
Thanks for the patch, nice idea!

Couple of remarks:
* calling a network service from a getter is not the best thing. This could block the UI, or just request the same information over and over again. Could you please move this call to NewPipeService.getDetails? 
* please make it optional, so if someone doesn't want to use that network service, they could opt out with a simple click in the preferences!

**Comment by gzsombor** [comment]
Could you please add a checkbox to a preference page, which could enable/disable this feature?

**Comment by gzsombor** [comment]
Why did you put back the networking call into YoutubeVideo class?

**Comment by gzsombor** [comment]
Thanks for the patch!

**Comment by drogga** [comment]
The dislikes count isn't showing up on the videos from thr feed (subscriptions), this needs a bit of more work...

**Comment by drogga** [comment]
@andrisas, @gzsombor
The dislikes count isn't showing up on the videos from the feed (subscriptions), this needs a bit of more work...

**Pull request merged**
