### PR TITLE
README reworked

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by gzsombor** [comment]
Thanks for the patch! However, it looks like, that the screenshots are not rendered correctly by Github - are you aware of?

**Comment by comradekingu** [comment]
@gzombor Yes, but it should™ work. They were broken before, and then I tried just fixing it like it was, and GitHub wasn't showing the first image correctly.

**Comment by gzsombor** [comment]
Yes, it was broken before, because the images disappeared due to the repository move - I guess.

**Comment by gzsombor** [comment]
Thanks for the patch, after I put the html fragments back, everything looks ok :+1:

**Pull request merged**
