### PR TITLE
Fix Images in the README

### PR DESCRIPTION
**Pull request by gzsombor**

### CODE REVIEW

**Comment by drogga** [comment]
@gzsombor There's still 1 broken...

**Comment by drogga** [comment]
@gzsombor There's still 1 broken (called "Browse channel using tablet"), but the next one shows exactly that, so it's a mess there...

Also the GPL 3 one is too large and stretched (pixalated) now.

**Comment by drogga** [comment]
@gzsombor There's still 1 broken (called "Browse channel using tablet"), but the next one shows exactly that, so it's a mess there...

Also the GPL 3 one is too large and stretched (pixalated) now.

**Comment by gzsombor** [comment]
At least, I could fix the GPL image, the other one... This is the original size of the picture, I think

**Pull request merged**
