### PR TITLE
Fixed typo in cleaner's toast, which was broken

### PR DESCRIPTION
**Pull request by drogga**

### CODE REVIEW

**Comment by drogga** [comment]
You migh want to search and replace other similar typos if available, because I think there are, but I'm editing from a browser so I can't.

**Comment by drogga** [comment]
@gzsombor What about this one ?

**Comment by drogga** [comment]
@gzsombor Please merge before the new release because I can't do it myself.

**Comment by drogga** [comment]
@mckaygerhard can you pls. mention/tag gzsombor as wll here to back me up, because I'm afraid that he doesn't get notified when I do it and I don't want this to stay here for even more months and the new ver. if released officially to be without it. Thank You.

**Comment by gzsombor** [comment]
Thanks for the patch, it looks better!

**Pull request merged**
