### PR TITLE
Use view binding.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**

### CODE REVIEW

**Comment by gzsombor** [comment]
Nice! Always a good feeling, when one can remove a lot of unnecessary code :+1:

**Comment by gzsombor** [comment]
And this one also fails...

**Comment by Isira-Seneviratne** [comment]
The `extra` variant builds fine, though.

**Comment by gzsombor** [comment]
I see, yes, you can't refer to the chromecast related fields in the OSS variant.

**Comment by gzsombor** [comment]
@Isira-Seneviratne , sorry, but the CI build fails and there is a lot of merge conflict in these patch, could you have a look on it? Do you plan to fix it?

**Comment by gzsombor** [comment]
Thanks @Isira-Seneviratne  for the initial patch, I had to rebase and fix the compilation errors, but now it looks and works great!

**Pull request closed without merging**
